In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv('heart.csv')
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0     125.0   212    0      NaN    168.0      0      1.0   
1      53    1   0     140.0   203    1      0.0    155.0      1      3.1   
2      70    1   0     145.0   174    0      1.0    125.0      1      2.6   
3      61    1   0     148.0   203    0      1.0      NaN      0      0.0   
4      62    0   0     138.0   294    1      1.0    106.0      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1     140.0   221    0      1.0    164.0      1      0.0   
1021   60    1   0     125.0   258    0      0.0    141.0      1      2.8   
1022   47    1   0     110.0   275    0      0.0    118.0      1      1.0   
1023   50    0   0     110.0   254    0      0.0    159.0      0      0.0   
1024   54    1   0     120.0   188    0      1.0    113.0      0      1.4   

      slope   ca  thal  target  
0         2  2.0   3.0       0  
1         0  0.0   3.0       0  
2         0  0.0   3.0       0  
3         2  1.0   3.0       0  
4         1  3.0   2.0       0  
...     ...  ...   ...     ...  
1020      2  0.0   2.0       1  
1021      1  1.0   3.0       0  
1022      1  1.0   2.0       0  
1023      2  0.0   2.0       1  
1024      1  1.0   3.0       0  

[1025 rows x 14 columns]

In [2]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0     125.0   212    0      NaN    168.0      0      1.0      2   
1   53    1   0     140.0   203    1      0.0    155.0      1      3.1      0   
2   70    1   0     145.0   174    0      1.0    125.0      1      2.6      0   
3   61    1   0     148.0   203    0      1.0      NaN      0      0.0      2   
4   62    0   0     138.0   294    1      1.0    106.0      0      1.9      1   

    ca  thal  target  
0  2.0   3.0       0  
1  0.0   3.0       0  
2  0.0   3.0       0  
3  1.0   3.0       0  
4  3.0   2.0       0

In [3]:
df.tail()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
1020   59    1   1     140.0   221    0      1.0    164.0      1      0.0   
1021   60    1   0     125.0   258    0      0.0    141.0      1      2.8   
1022   47    1   0     110.0   275    0      0.0    118.0      1      1.0   
1023   50    0   0     110.0   254    0      0.0    159.0      0      0.0   
1024   54    1   0     120.0   188    0      1.0    113.0      0      1.4   

      slope   ca  thal  target  
1020      2  0.0   2.0       1  
1021      1  1.0   3.0       0  
1022      1  1.0   2.0       0  
1023      2  0.0   2.0       1  
1024      1  1.0   3.0       0

In [4]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps    float64
chol          int64
fbs           int64
restecg     float64
thalach     float64
exang         int64
oldpeak     float64
slope         int64
ca          float64
thal        float64
target        int64
dtype: object

In [5]:
df.ndim

2

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1024 non-null   float64
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1024 non-null   float64
 7   thalach   1024 non-null   float64
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1023 non-null   float64
 12  thal      1024 non-null   float64
 13  target    1025 non-null   int64  
dtypes: float64(6), int64(8)
memory usage: 112.2 KB


In [7]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    1
chol        0
fbs         0
restecg     1
thalach     1
exang       0
oldpeak     0
slope       0
ca          2
thal        1
target      0
dtype: int64

In [8]:
df['trestbps'].unique()

array([125., 140., 145., 148., 138., 100., 114., 160., 120., 122., 112.,
       132., 118., 128.,  nan, 124., 106., 104., 135., 130., 136., 180.,
       129., 150., 178., 146., 117., 152., 154., 170., 134., 174., 144.,
       108., 123., 110., 142., 126., 192., 115.,  94., 200., 165., 102.,
       105., 155., 172., 164., 156., 101.])

In [9]:
df['restecg'].unique()
df['thalach'].unique()
df['ca'].unique()
df['thal'].unique()

array([ 3.,  2.,  1.,  0., nan])

In [10]:
# x1=df['trestbps'].mean()
# df['trestbps'].fillna(x1,inplace=True)

# x2=df['restecg'].mode()[0]
# df['restecg'].fillna(x2,inplace=True)

# x3=df['thalach'].mean()
# df['thalach'].fillna(x3,inplace=True)

# x4=df['ca'].mode()[0]
# df['ca'].fillna(x4,inplace=True)

# x5=df['thal'].mode()[0]
# df['thal'].fillna(x4,inplace=True)

#                    OR

df['trestbps']=df['trestbps'].fillna(df['trestbps'].mean())
df['restecg']=df['restecg'].fillna(df['restecg'].mode()[0])
df['thalach']=df['thalach'].fillna(df['thalach'].mean())
df['ca']=df['ca'].fillna(df['ca'].mode()[0])
df['thal']=df['thal'].fillna(df['thal'].mode()[0])



df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [11]:
df['target'].value_counts()

target
1    526
0    499
Name: count, dtype: int64

In [12]:
x=df.iloc[:,:-1].values
x

array([[52.,  1.,  0., ...,  2.,  2.,  3.],
       [53.,  1.,  0., ...,  0.,  0.,  3.],
       [70.,  1.,  0., ...,  0.,  0.,  3.],
       ...,
       [47.,  1.,  0., ...,  1.,  1.,  2.],
       [50.,  0.,  0., ...,  2.,  0.,  2.],
       [54.,  1.,  0., ...,  1.,  1.,  3.]], shape=(1025, 13))

In [13]:
y=df.iloc[:,-1].values
y

array([0, 0, 0, ..., 0, 1, 0], shape=(1025,))

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=1)
x_train

array([[62.,  0.,  0., ...,  1.,  3.,  2.],
       [68.,  1.,  2., ...,  1.,  0.,  3.],
       [66.,  0.,  2., ...,  1.,  1.,  2.],
       ...,
       [56.,  1.,  0., ...,  1.,  1.,  2.],
       [62.,  1.,  0., ...,  1.,  2.,  3.],
       [64.,  1.,  3., ...,  1.,  0.,  3.]], shape=(717, 13))

In [15]:
y_train

array([0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,

In [16]:
x_test

array([[60.,  1.,  0., ...,  2.,  2.,  3.],
       [51.,  0.,  2., ...,  2.,  0.,  2.],
       [42.,  1.,  1., ...,  2.,  0.,  2.],
       ...,
       [64.,  0.,  2., ...,  2.,  0.,  3.],
       [42.,  1.,  0., ...,  2.,  0.,  2.],
       [51.,  1.,  2., ...,  2.,  1.,  3.]], shape=(308, 13))

In [17]:
y_test

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,

In [18]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train) #taking x-train
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[ 0.84287068, -1.49322796, -0.92148277, ..., -0.61823273,
         2.20430609, -0.52060454],
       [ 1.51262126,  0.66969011,  1.08368611, ..., -0.61823273,
        -0.72071698,  1.10232353],
       [ 1.28937106, -1.49322796,  1.08368611, ..., -0.61823273,
         0.25429071, -0.52060454],
       ...,
       [ 0.17312009,  0.66969011, -0.92148277, ..., -0.61823273,
         0.25429071, -0.52060454],
       [ 0.84287068,  0.66969011, -0.92148277, ..., -0.61823273,
         1.2292984 ,  1.10232353],
       [ 1.06612087,  0.66969011,  2.08627055, ..., -0.61823273,
        -0.72071698,  1.10232353]], shape=(717, 13))

In [19]:
x_test

array([[ 0.61962048,  0.66969011, -0.92148277, ...,  0.98203033,
         1.2292984 ,  1.10232353],
       [-0.38500539, -1.49322796,  1.08368611, ...,  0.98203033,
        -0.72071698, -0.52060454],
       [-1.38963126,  0.66969011,  0.08110167, ...,  0.98203033,
        -0.72071698, -0.52060454],
       ...,
       [ 1.06612087, -1.49322796,  1.08368611, ...,  0.98203033,
        -0.72071698,  1.10232353],
       [-1.38963126,  0.66969011, -0.92148277, ...,  0.98203033,
        -0.72071698, -0.52060454],
       [-0.38500539,  0.66969011,  1.08368611, ...,  0.98203033,
         0.25429071,  1.10232353]], shape=(308, 13))

In [20]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=7)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
y_pred

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,

In [21]:
y_test

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,

In [22]:
print(knn.predict(scaler.transform([[23,1,3,568.0,230,1,1.0,160.0,0,1.5,2,2.0,3.0]])))

[0]


In [23]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_pred,y_test)
cm

array([[130,  12],
       [ 31, 135]])

In [24]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_pred,y_test)
acc

0.8603896103896104

In [25]:
from sklearn.metrics import classification_report
cr=classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.92      0.81      0.86       161
           1       0.81      0.92      0.86       147

    accuracy                           0.86       308
   macro avg       0.86      0.86      0.86       308
weighted avg       0.87      0.86      0.86       308

